from tkinter import*;
root=Tk()
root.geometry("600x400")
root.title("Notepad")
root.iconbitmap("favicon.ico")
# f2=Frame(root,bg="sky blue",width=10,borderwidth=5,relief="sunken")
# f2.pack(side="left",fill=Y)
f1=Frame(root,bg="grey",height=50)
f1.pack(side="top",fill=X)
b1=Button(f1,text="New   ",bg="grey")
b1.grid(row=0)
b2=Button(f1,text="Save",bg="grey")
b2.grid(row=0,column=1)
b3=Button(f1,text="Print   ",bg="grey")
b3.grid(row=0,column=2)
b4=Button(f1,text="Zoom in/out   ",bg="grey")
b4.grid(row=0,column=3)
b5=Button(f1,text="Exit   ",command=quit,bg="grey")
b5.grid(row=0,column=4)
f3=Frame(root,bg='#36454F',width=2000,borderwidth=5)
f3.pack(side="right",fill=Y,)


root.mainloop()